name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      # Линтинг и тесты отключены, т.к. у тебя пока их нет
